In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.rand((4,8)))
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))

    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)

linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 1.2648, -1.2138, -0.6748],
        [-0.0369, -1.0866,  0.1367],
        [-1.2023, -0.7454, -1.4862],
        [ 2.1399, -1.3201, -0.5928],
        [-1.7694,  1.3518,  1.9013]], requires_grad=True)

In [6]:
linear(torch.randn(2,5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 3.6358, 0.8152]])

In [7]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.randn(2,64))

tensor([[24.1035],
        [21.7434]])